pull_request_rules:
  - name: automatic merge when 2 reviews and we know the person
    conditions:
      - base=master
      - approved-reviews-by>=1
    actions:
      merge:
        method: merge
  - name: automatic merge for technology representative of country - india
    conditions:
      - base=master
      - author=beeeku
      - files=india.md
    actions:
      merge:
        method: merge
  - name: automatic merge for technology representative of country - india 2
    conditions:
      - base=master
      - author=ajaytantry
      - files=india.md
    actions:
      merge:
        method: merge
        