name: trigger GitHub pages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo 'test works'
      - name: Run a multi-line script
        if: github.actor != 'noelelias'
        run: |
          echo 'started push'
          git clone https://github.com/Yes-Theory:<${{ secrets.personalAccessToken }}>@github.com/Yes-Theory/yes-theory.github.io
          git config user.name "noelelias"
          git config user.email "schenknoel@gmail.com"
          git commit -m 'trigger github pages' --allow-empty
          git push origin master
